"""Shared typed surface for POSIX pexpect and Windows ConPTY drivers."""

from __future__ import annotations

from typing import Protocol, TextIO


class TerminalProcess(Protocol):
    @property
    def pid(self) -> int | None: ...

    @property
    def exitstatus(self) -> int | None: ...

    def set_logfile_read(self, logfile: TextIO | None) -> None: ...

    def matched_group(self, index: int) -> str: ...

    def send(self, value: str) -> int: ...

    def setwinsize(self, rows: int, columns: int) -> None: ...

    def expect_exact(self, pattern: str, timeout: float | None = None) -> int: ...

    def expect(self, pattern: str, timeout: float | None = None) -> int: ...

    def expect_eof(self, timeout: float | None = None) -> None: ...

    def terminate(self, force: bool = False) -> bool: ...

    def close(self, force: bool = False) -> None: ...

    def isalive(self) -> bool: ...
