// Generated by scripts/native/sync_version.py. Do not edit by hand.
//
// The single source of this identity is the `version` field of pyproject.toml.

/// The Birkin package version this application was built from.
public enum BirkinVersion {
    public static let packageVersion = "0.4.285"
}
