#!/usr/bin/env python3
"""Generate the Swift version seam from the Python package manifest.

The macOS application, its protocol vectors, and the disk image all take their
identity from ``pyproject.toml``. This script is the only writer of that
identity into Swift, so a package version bump never needs a hand-edited
literal.

Usage:
    python3 scripts/native/sync_version.py            # write the seam
    python3 scripts/native/sync_version.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import sys
import tomli as tomllib
from pathlib import Path
from typing import TypeGuard, cast

REPOSITORY = Path(__file__).resolve().parent.parent.parent
MANIFEST = REPOSITORY / "pyproject.toml"
GENERATED = (
    REPOSITORY
    / "macos/BirkinNativeApp/Sources/BirkinNativeProtocol/BirkinVersion.swift"
)

_TEMPLATE = '''// Generated by scripts/native/sync_version.py. Do not edit by hand.
//
// The single source of this identity is the `version` field of pyproject.toml.

/// The Birkin package version this application was built from.
public enum BirkinVersion {{
    public static let packageVersion = "{version}"
}}
'''


def _is_string_keyed_table(value: object) -> TypeGuard[dict[str, object]]:
    return isinstance(value, dict)


def package_version() -> str:
    """Read the canonical package version from the Python manifest."""
    with MANIFEST.open("rb") as handle:
        manifest = cast(object, tomllib.load(handle))
    if not _is_string_keyed_table(manifest):
        raise ValueError("pyproject.toml has no [project] table")
    project = manifest["project"]
    if not _is_string_keyed_table(project):
        raise ValueError("pyproject.toml has no [project] table")
    version = project["version"]
    if not isinstance(version, str) or not version:
        raise ValueError("pyproject.toml declares no project version")
    return version


def render() -> str:
    return _TEMPLATE.format(version=package_version())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the generated seam is stale",
    )
    _ = parser.parse_args(argv)
    check = "--check" in (sys.argv[1:] if argv is None else argv)
    expected = render()
    current = GENERATED.read_text(encoding="utf-8") if GENERATED.exists() else ""
    if check:
        if current != expected:
            print(
                f"{GENERATED.relative_to(REPOSITORY)} is stale; "
                + "run scripts/native/sync_version.py",
                file=sys.stderr,
            )
            return 1
        print(f"version seam is current at {package_version()}")
        return 0
    if current != expected:
        GENERATED.parent.mkdir(parents=True, exist_ok=True)
        _ = GENERATED.write_text(expected, encoding="utf-8")
    print(f"version seam written at {package_version()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
