#!/usr/bin/env python3
"""Generate the Swift version seam from the Python package manifest.

The macOS application, its protocol vectors, and the disk image all take their
identity from ``pyproject.toml``. This script is the only writer of that
identity into Swift, so a package version bump never needs a hand-edited
literal.

``--all`` extends that seam to every other artifact the version leaks into,
so the per-commit patch bump can never leave the Swift seam, the golden
vectors, the lock file, the published docs, or the helper input checksums a
release behind.

Usage:
    python3 scripts/native/sync_version.py                 # write the seam
    python3 scripts/native/sync_version.py --check         # fail if it is stale
    python3 scripts/native/sync_version.py --all           # write every artifact
    python3 scripts/native/sync_version.py --check --all   # verify every artifact
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import tomli as tomllib
from pathlib import Path
from typing import TypeGuard, cast

REPOSITORY = Path(__file__).resolve().parent.parent.parent
MANIFEST = REPOSITORY / "pyproject.toml"
GENERATED = (
    REPOSITORY
    / "macos/BirkinNativeApp/Sources/BirkinNativeProtocol/BirkinVersion.swift"
)
UV_LOCK = REPOSITORY / "uv.lock"
BRIDGE_INPUTS = REPOSITORY / "scripts/native/bridge_helper_inputs.json"
DOCUMENTS = (
    REPOSITORY / "README.md",
    REPOSITORY / "README.ko.md",
    REPOSITORY / "docs/office-support.md",
)

# The editable "birkin" entry of uv.lock restates the manifest version.
_LOCKED_VERSION = re.compile(r'(?m)^(name = "birkin"\nversion = ")\d+\.\d+\.\d+(")')
# "Birkin `0.0.0`" and "Birkin version: `0.0.0`" are the published mentions.
_DOCUMENTED_VERSION = re.compile(r"(Birkin (?:version: )?`)\d+\.\d+\.\d+(`)")
_PROJECT_DIGEST = re.compile(r'"(pyproject_sha256|uv_lock_sha256)": "[0-9a-f]{64}"')

_TEMPLATE = '''// Generated by scripts/native/sync_version.py. Do not edit by hand.
//
// The single source of this identity is the `version` field of pyproject.toml.

/// The Birkin package version this application was built from.
public enum BirkinVersion {{
    public static let packageVersion = "{version}"
}}
'''


def _is_string_keyed_table(value: object) -> TypeGuard[dict[str, object]]:
    return isinstance(value, dict)


def package_version() -> str:
    """Read the canonical package version from the Python manifest."""
    with MANIFEST.open("rb") as handle:
        manifest = cast(object, tomllib.load(handle))
    if not _is_string_keyed_table(manifest):
        raise ValueError("pyproject.toml has no [project] table")
    project = manifest["project"]
    if not _is_string_keyed_table(project):
        raise ValueError("pyproject.toml has no [project] table")
    version = project["version"]
    if not isinstance(version, str) or not version:
        raise ValueError("pyproject.toml declares no project version")
    return version


def render() -> str:
    return _TEMPLATE.format(version=package_version())


def set_locked_version(lock: str, version: str) -> str:
    """Restate the manifest version in the editable "birkin" lock entry."""
    return _LOCKED_VERSION.sub(rf"\g<1>{version}\g<2>", lock, count=1)


def set_documented_version(document: str, version: str) -> str:
    """Rewrite the published Birkin version mentions, leaving prose alone."""
    return _DOCUMENTED_VERSION.sub(rf"\g<1>{version}\g<2>", document)


def set_project_digests(descriptor: str, *, pyproject: bytes, lock: bytes) -> str:
    """Re-pin the helper build inputs to the bytes they now describe."""
    digests = {
        "pyproject_sha256": _digest(pyproject),
        "uv_lock_sha256": _digest(lock),
    }
    return _PROJECT_DIGEST.sub(
        lambda match: f'"{match[1]}": "{digests[match[1]]}"', descriptor
    )


def _digest(payload: bytes) -> str:
    """Hash a checkout artifact the way the helper builder verifies it."""
    return hashlib.sha256(payload.replace(b"\r\n", b"\n")).hexdigest()


def _generated_vectors() -> list[tuple[Path, str]]:
    """Re-render the cross-language fixtures from this checkout's codec."""
    sys.path.insert(0, str(REPOSITORY))
    from scripts.native.generate_golden_vectors import (
        FIXTURE_PATH,
        INVALID_FIXTURE_PATH,
        render_fixture,
        render_invalid_fixture,
    )
    from scripts.native.generate_projection_vectors import (
        FIXTURE_PATH as PROJECTION_PATH,
    )
    from scripts.native.generate_projection_vectors import (
        render_fixture as render_projection,
    )

    return [
        (FIXTURE_PATH, render_fixture()),
        (INVALID_FIXTURE_PATH, render_invalid_fixture()),
        (PROJECTION_PATH, render_projection()),
    ]


def derived_outputs(every: bool) -> list[tuple[Path, str]]:
    """The content every derived artifact must hold for the manifest version."""
    if not every:
        return [(GENERATED, render())]
    version = package_version()
    lock = set_locked_version(UV_LOCK.read_text(encoding="utf-8"), version)
    outputs = [
        (GENERATED, render()),
        (UV_LOCK, lock),
        *_generated_vectors(),
        *(
            (
                document,
                set_documented_version(document.read_text(encoding="utf-8"), version),
            )
            for document in DOCUMENTS
        ),
    ]
    outputs.append(
        (
            BRIDGE_INPUTS,
            set_project_digests(
                BRIDGE_INPUTS.read_text(encoding="utf-8"),
                pyproject=MANIFEST.read_bytes(),
                lock=lock.encode("utf-8"),
            ),
        )
    )
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the generated seam is stale",
    )
    _ = parser.add_argument(
        "--all",
        action="store_true",
        help="sync every derived artifact, not only the Swift seam",
    )
    _ = parser.parse_args(argv)
    flags = sys.argv[1:] if argv is None else argv
    check = "--check" in flags
    outputs = derived_outputs("--all" in flags)
    stale = [
        (path, expected)
        for path, expected in outputs
        if (path.read_text(encoding="utf-8") if path.exists() else "") != expected
    ]
    if check:
        if stale:
            for path, _expected in stale:
                print(
                    f"{path.relative_to(REPOSITORY).as_posix()} is stale; "
                    + "run scripts/native/sync_version.py --all",
                    file=sys.stderr,
                )
            return 1
        print(f"version seam is current at {package_version()}")
        return 0
    for path, expected in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        _ = path.write_text(expected, encoding="utf-8")
    print(f"version seam written at {package_version()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
