from collections.abc import Mapping, Sequence

class WinptyError(Exception): ...

class PTY:
    def cancel_io(self) -> bool: ...

class PtyProcess:
    pty: PTY
    pid: int | None
    exitstatus: int | None

    @classmethod
    def spawn(
        cls,
        argv: Sequence[str],
        cwd: str | None = ...,
        env: Mapping[str, str] | None = ...,
        dimensions: tuple[int, int] = ...,
        backend: int | None = ...,
    ) -> PtyProcess: ...

    def read(self, size: int = ...) -> str: ...
    def write(self, s: str) -> int: ...
    def setwinsize(self, rows: int, cols: int) -> None: ...
    def close(self, force: bool = ...) -> None: ...
    def isalive(self) -> bool: ...
    def wait(self) -> int | None: ...
